/*
 * auth.js — shared password gate for the R203 reports site.
 *
 * WHAT THIS IS: a deterrence layer. It keeps casual visitors, mis-shared links
 * and search engines out of the reports. It is NOT confidentiality — this repo
 * is public, so anyone who thinks to browse github.com/leeroy-cmyk/reports can
 * still read data/*.json directly. If the data ever needs to be genuinely
 * private, the repo has to go private and hosting has to move off GitHub Pages.
 *
 * To change the password:  node set-password.js "your new password"
 */
(function () {
  'use strict';

  // ---- generated by set-password.js — do not hand-edit ----
  var CONFIG = {
    salt: '0f3cb641f81440805b23ccbee77d7d9d',
    hash: '51a21e05d97b264e42ce1bd267d7ab4fd7db1ee2c5285140f0d8134dd58b9794',
    iterations: 200000
  };
  // ---------------------------------------------------------

  var STORE_KEY = 'r203_reports_auth';
  var REMEMBER_DAYS = 30;

  // Hide the page immediately, before anything paints. visibility (not display)
  // so the login overlay can opt itself back in as a child of a hidden body.
  var lockStyle = document.createElement('style');
  lockStyle.textContent =
    'html.r203-locked{overflow:hidden}' +
    'html.r203-locked>body{visibility:hidden}' +
    'html.r203-locked>body>#r203-gate{visibility:visible}';
  document.documentElement.appendChild(lockStyle);
  document.documentElement.className += ' r203-locked';

  function unlock() {
    document.documentElement.className =
      document.documentElement.className.replace(/\s*r203-locked/g, '');
    var gate = document.getElementById('r203-gate');
    if (gate) gate.parentNode.removeChild(gate);
  }

  function toHex(buf) {
    var out = '';
    var bytes = new Uint8Array(buf);
    for (var i = 0; i < bytes.length; i++) {
      out += ('0' + bytes[i].toString(16)).slice(-2);
    }
    return out;
  }

  function hexToBytes(hex) {
    var bytes = new Uint8Array(hex.length / 2);
    for (var i = 0; i < bytes.length; i++) {
      bytes[i] = parseInt(hex.substr(i * 2, 2), 16);
    }
    return bytes;
  }

  // PBKDF2-SHA256, same parameters as set-password.js, so a brute-force attempt
  // against the hash in this file costs real time per guess.
  function derive(password) {
    var enc = new TextEncoder();
    return crypto.subtle
      .importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveBits'])
      .then(function (key) {
        return crypto.subtle.deriveBits(
          {
            name: 'PBKDF2',
            salt: hexToBytes(CONFIG.salt),
            iterations: CONFIG.iterations,
            hash: 'SHA-256'
          },
          key,
          256
        );
      })
      .then(toHex);
  }

  // ---- already signed in? ----
  function storedSessionValid() {
    try {
      var raw = localStorage.getItem(STORE_KEY);
      if (!raw) return false;
      var saved = JSON.parse(raw);
      if (saved.token !== CONFIG.hash) return false;   // password has changed
      if (!saved.exp || Date.now() > saved.exp) return false;
      return true;
    } catch (e) {
      return false;
    }
  }

  if (storedSessionValid()) {
    unlock();
    return;
  }

  // ---- login overlay ----
  var CSS =
    '#r203-gate{position:fixed;inset:0;z-index:2147483647;background:#f4f6f9;' +
      'display:flex;align-items:center;justify-content:center;padding:24px;' +
      "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}" +
    '#r203-gate .box{background:#fff;border:1px solid #e8ecf0;border-radius:10px;' +
      'box-shadow:0 4px 24px rgba(26,82,118,.12);padding:32px;width:100%;max-width:360px}' +
    '#r203-gate h1{margin:0 0 4px;font-size:1.15rem;font-weight:700;color:#1a5276}' +
    '#r203-gate p.sub{margin:0 0 20px;font-size:.82rem;color:#7f8c8d}' +
    '#r203-gate label{display:block;font-size:.72rem;font-weight:700;letter-spacing:.06em;' +
      'text-transform:uppercase;color:#7f8c8d;margin-bottom:6px}' +
    '#r203-gate input{width:100%;padding:10px 12px;font-size:.95rem;color:#2c3e50;' +
      'border:1px solid #d6dee6;border-radius:6px;background:#fff}' +
    '#r203-gate input:focus{outline:none;border-color:#2e86c1;box-shadow:0 0 0 3px rgba(46,134,193,.14)}' +
    '#r203-gate button{width:100%;margin-top:16px;padding:10px 12px;font-size:.9rem;' +
      'font-weight:600;color:#fff;background:#1a5276;border:0;border-radius:6px;cursor:pointer}' +
    '#r203-gate button:hover{background:#2e86c1}' +
    '#r203-gate button[disabled]{opacity:.6;cursor:default}' +
    '#r203-gate .err{margin-top:12px;font-size:.82rem;color:#922b21;min-height:1.1em}' +
    '#r203-gate .remember{margin-top:14px;font-size:.8rem;color:#5d6d7e;display:flex;' +
      'align-items:center;gap:8px}' +
    '#r203-gate .remember input{width:auto;margin:0}';

  function buildGate() {
    var style = document.createElement('style');
    style.textContent = CSS;
    document.head.appendChild(style);

    var gate = document.createElement('div');
    gate.id = 'r203-gate';
    gate.innerHTML =
      '<div class="box">' +
        '<h1>R203 Reports</h1>' +
        '<p class="sub">Maintenance &amp; Construction — internal dashboard</p>' +
        '<form id="r203-form">' +
          '<label for="r203-pw">Password</label>' +
          '<input type="password" id="r203-pw" autocomplete="current-password" autofocus>' +
          '<label class="remember"><input type="checkbox" id="r203-remember" checked>' +
            'Keep me signed in on this device</label>' +
          '<button type="submit" id="r203-go">Sign in</button>' +
          '<div class="err" id="r203-err"></div>' +
        '</form>' +
      '</div>';
    document.body.appendChild(gate);

    var form = document.getElementById('r203-form');
    var input = document.getElementById('r203-pw');
    var err = document.getElementById('r203-err');
    var btn = document.getElementById('r203-go');
    input.focus();

    form.addEventListener('submit', function (ev) {
      ev.preventDefault();
      err.textContent = '';
      btn.disabled = true;
      btn.textContent = 'Checking…';

      derive(input.value).then(function (digest) {
        if (digest === CONFIG.hash) {
          if (document.getElementById('r203-remember').checked) {
            try {
              localStorage.setItem(STORE_KEY, JSON.stringify({
                token: digest,
                exp: Date.now() + REMEMBER_DAYS * 86400000
              }));
            } catch (e) { /* private browsing — session-only is fine */ }
          }
          unlock();
        } else {
          btn.disabled = false;
          btn.textContent = 'Sign in';
          err.textContent = 'Incorrect password.';
          input.value = '';
          input.focus();
        }
      }).catch(function () {
        btn.disabled = false;
        btn.textContent = 'Sign in';
        err.textContent = 'Could not verify — this page must be served over http(s), not opened as a file.';
      });
    });
  }

  if (document.body) {
    buildGate();
  } else {
    document.addEventListener('DOMContentLoaded', buildGate);
  }
})();
